apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{- .Release.Name  }}-configmap"
  namespace: {{ .Release.Namespace }}
data:
  config.yaml: |
    protocol: {{ toYaml .Values.config.protocol }}
    {{- if eq .Values.config.protocol "nats" }}
    nats:
{{ toYaml .Values.config.nats | indent 6 }}
    {{- end}}
    {{- if eq .Values.config.protocol "natsJetstream" }}
    natsJetstream:
{{ toYaml .Values.config.natsJetstream | indent 6 }}
    {{- end}}
    {{- if eq .Values.config.protocol "kafka" }}
    kafka:
{{ toYaml .Values.config.kafka | indent 6 }}
    {{- end}}
    {{- if eq .Values.config.protocol "http" }}
    http:
{{ toYaml .Values.config.http | indent 6 }}
    {{- end}}
    {{- if eq .Values.config.protocol "mqtt" }}
    mqtt:
{{ toYaml .Values.config.mqtt | indent 6 }}
    {{- end}}
    {{- if eq .Values.config.protocol "ampq" }}
    ampq:
{{ toYaml .Values.config.ampq | indent 6 }}
    {{- end}}
    keywords:
{{ toYaml .Values.config.keywords | indent 6 }}