apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{- .Release.Name  }}-deployment"
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      annotations:
      {{- if .Values.podAnnotations }}
      {{ toYaml .Values.podAnnotations | indent 8 }}
      {{- end }}
    spec:
      imagePullSecrets:
        - name: {{ .Values.image.pullSecrets }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}/{{ .Values.image.name }}:{{ default .Chart.AppVersion .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
          volumeMounts:
            - mountPath: /app
              name: config-volume
      {{- if .Values.resources }}
          resources:
{{ toYaml .Values.resources | indent 10 }}
      {{- end }}
      volumes:
        - name: config-volume
          configMap:
            name: "{{ .Release.Name }}-configmap"
